"""update user table

Revision ID: 0f9011984558
Revises: 94e273ac7764
Create Date: 2025-09-25 00:06:54.972693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f9011984558'
down_revision: Union[str, None] = '94e273ac7764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phantombuster_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phantombuster_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
