"""added new table

Revision ID: 94e273ac7764
Revises: add_google_oauth_fields
Create Date: 2025-09-24 15:50:02.735540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94e273ac7764'
down_revision: Union[str, None] = 'add_google_oauth_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lead', sa.Column('email_confidence', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lead_email'), 'lead', ['email'], unique=False)
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_index(op.f('ix_lead_email'), table_name='lead')
    op.drop_column('lead', 'email_confidence')
    op.drop_column('lead', 'email')
    # ### end Alembic commands ###
