"""added table

Revision ID: c1e3af0fb1df
Revises: 
Create Date: 2025-09-22 14:31:28.516517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql 
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c1e3af0fb1df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailcampaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emaillog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('to_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['emailcampaign.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('campaign', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('lead', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('lead', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('lead', 'profile_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('lead', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'ACCEPTED', 'REPLIED', 'FAILED', name='leadstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('lead', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('lead', 'created_at')
    op.alter_column('outreachlog', 'status',
               existing_type=postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='outreachstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('outreachlog', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('user', sa.Column('phantombuster_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('paystack_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'subscription_tier',
               existing_type=postgresql.ENUM('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptiontier'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('user', 'subscription_tier',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptiontier'),
               existing_nullable=False)
    op.drop_column('user', 'subscription_expires_at')
    op.drop_column('user', 'subscription_status')
    op.drop_column('user', 'paystack_customer_id')
    op.drop_column('user', 'phantombuster_api_key')
    op.alter_column('outreachlog', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('outreachlog', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='outreachstatus'),
               existing_nullable=False)
    op.add_column('lead', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('lead', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lead', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('PENDING', 'SENT', 'ACCEPTED', 'REPLIED', 'FAILED', name='leadstatus'),
               existing_nullable=False)
    op.alter_column('lead', 'profile_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('lead', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('lead', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('campaign', 'status')
    op.drop_column('campaign', 'description')
    op.drop_table('emaillog')
    op.drop_table('emailcampaign')
    # ### end Alembic commands ###
